### ISSUE TITLE
location jump during driving

### ISSUE THREAD

**Issue by sajjadintel** [eusonlito/GPS-Tracker#40]
Hi,
There's a problem when I come out of the parking, GPS hasn't locked yet and there's some wired location jumps.
Is it possible to ignore locations that are not logical? for example car speed is 0 but next location is far from the previous one.
Thanks.

https://tracker.lito.com.es/trip/1842/map
(I think in this one car went into the parking and came out.)
![telegram-cloud-photo-size-4-5884027946694459841-y](https://github.com/eusonlito/GPS-Tracker/assets/13988374/a01ce72f-0f78-4e88-9462-90f2ab10197c)

https://tracker.lito.com.es/?trip_id=1850
I found a location jump when I was driving. do you have any idea why this has happened and is it possible to fix it? (Could it be cloud and snowing?)
![image](https://github.com/eusonlito/GPS-Tracker/assets/13988374/7ba9e1c8-0791-4cab-b0f1-e103757c867d)

**Comment by eusonlito** [comment]
The "problem" is that the device is reporting those positions as valid, so it is not possible to avoid those jumps.

I have configured the platform to accept only positions marked as valid, and with a minimum displacement of 10 meters (default is 5), so if the device indicates that they are correct, the system has no way of knowing if they really are.

![image](https://github.com/eusonlito/GPS-Tracker/assets/644551/8e808857-44dd-404d-915e-06194103753c)

**Comment by sajjadintel** [comment]
Can't we detect jumps by car speed and distance between locations and don't register these items?

**Comment by eusonlito** [comment]
It's not easy, since the device sends records every 10 seconds, and in those 10 seconds there can be movement.

Second 00 - Speed = 0 - Report to Platform.
Second 01 - Speed = 05 (movement).
Second 02 - Speed = 20 (movement).
Second 03 - Speed = 40 (movement).
Second 04 - Speed = 50 (movement).
Second 05 - Speed = 70 (movement).
Second 06 - Speed = 80 (movement).
Second 07 - Speed = 40 (movement).
Second 08 - Speed = 20 (movement).
Second 09 - Speed = 10 (movement).
Second 10 - Speed =  0 - Report to Platform.

Right now the platform is filtering locations by distance and valid signal (indicating that the location generated by the device is correct and not an offline cache), but there is little more that can be done.

**Comment by eusonlito** [comment]
Solved?

**Comment by sajjadintel** [comment]
Yeah, Thank you.
